### Create user

POST http://localhost:8080/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "login": "johndoe",
  "password": "jd_password",
  "userRole": "DEVELOPER"
}

### Get all users
GET http://localhost:8080/users

### Get users
GET http://localhost:8080/users/1

### Update user
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "userRole": "TESTER"
}

### Create team
POST http://localhost:8080/teams
Content-Type: application/json

{
  "name": "Wajchowi"
}

### Get all teams
GET http://localhost:8080/teams

### Get team
GET http://localhost:8080/teams/1

### Update team
PUT http://localhost:8080/teams/1
Content-Type: application/json

{
  "name": "Druciarze"
}

### Add team members
PUT http://localhost:8080/teams/1/members
Content-Type: application/json

{
  "userIds": [1]
}

### Get team
GET http://localhost:8080/teams/1

### Delete team members
DELETE http://localhost:8080/teams/1/members
Content-Type: application/json

{
  "userIds": [1]
}

### Get team
GET http://localhost:8080/teams/1

### Delete team
DELETE http://localhost:8080/teams/1

### Delete user
DELETE http://localhost:8080/users/1


