server:
  port: 8081
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
logging:
  level:
    sql: DEBUG
    org:
      springframework:
        orm:
          jpa: DEBUG
      hibernate:
        orm:
          jdbc:
            bind: TRACE